// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastLmMatrixLDLT
Rcpp::List fastLmMatrixLDLT(const Rcpp::NumericMatrix x, const Rcpp::NumericMatrix y, const double tol);
RcppExport SEXP _midnight_fastLmMatrixLDLT(SEXP xSEXP, SEXP ySEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fastLmMatrixLDLT(x, y, tol));
    return rcpp_result_gen;
END_RCPP
}
// fastLmMatrixLLT
Rcpp::List fastLmMatrixLLT(const Rcpp::NumericMatrix x, const Rcpp::NumericMatrix y);
RcppExport SEXP _midnight_fastLmMatrixLLT(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastLmMatrixLLT(x, y));
    return rcpp_result_gen;
END_RCPP
}
// fastLmMatrixQR
Rcpp::List fastLmMatrixQR(const Rcpp::NumericMatrix x, const Rcpp::NumericMatrix y);
RcppExport SEXP _midnight_fastLmMatrixQR(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastLmMatrixQR(x, y));
    return rcpp_result_gen;
END_RCPP
}
// fastLmMatrixSVD
Rcpp::List fastLmMatrixSVD(const Rcpp::NumericMatrix x, const Rcpp::NumericMatrix y, const double tol);
RcppExport SEXP _midnight_fastLmMatrixSVD(SEXP xSEXP, SEXP ySEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fastLmMatrixSVD(x, y, tol));
    return rcpp_result_gen;
END_RCPP
}
// fastLmMatrixUnpivotedQR
Rcpp::List fastLmMatrixUnpivotedQR(const Rcpp::NumericMatrix x, const Rcpp::NumericMatrix y);
RcppExport SEXP _midnight_fastLmMatrixUnpivotedQR(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastLmMatrixUnpivotedQR(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_midnight_fastLmMatrixLDLT", (DL_FUNC) &_midnight_fastLmMatrixLDLT, 3},
    {"_midnight_fastLmMatrixLLT", (DL_FUNC) &_midnight_fastLmMatrixLLT, 2},
    {"_midnight_fastLmMatrixQR", (DL_FUNC) &_midnight_fastLmMatrixQR, 2},
    {"_midnight_fastLmMatrixSVD", (DL_FUNC) &_midnight_fastLmMatrixSVD, 3},
    {"_midnight_fastLmMatrixUnpivotedQR", (DL_FUNC) &_midnight_fastLmMatrixUnpivotedQR, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_midnight(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
