# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastLmMatrixLDLT <- function(x, y, tol = 0.0000001) {
    .Call(`_midnight_fastLmMatrixLDLT`, x, y, tol)
}

fastLmMatrixLLT <- function(x, y) {
    .Call(`_midnight_fastLmMatrixLLT`, x, y)
}

fastLmMatrixQR <- function(x, y) {
    .Call(`_midnight_fastLmMatrixQR`, x, y)
}

fastLmMatrixSVD <- function(x, y, tol = 0.0000001) {
    .Call(`_midnight_fastLmMatrixSVD`, x, y, tol)
}

fastLmMatrixUnpivotedQR <- function(x, y) {
    .Call(`_midnight_fastLmMatrixUnpivotedQR`, x, y)
}

